# Generated by Django 4.2.4 on 2023-09-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
